architecture: standalone
auth:
  enabled: true
  rootPassword: "password123"
  username: "admin"
  password: "password123"
  database: "todoapp"

persistence:
  enabled: true
  size: 1Gi

service:
  type: ClusterIP
  port: 27017